### ISSUE TITLE
Kontakt zur Kontaktperson aufnehmen

### ISSUE THREAD

**Issue by meinkr4ft** [sweIhm/sweiproject-tg1a-6#10]
Als Benutzer will ich Kontakt zur Kontaktperson einer Akrivität aufnehmen, um genaue Informationen zu erhalten und mich daran beteiligen zu können.
Akzeptanzkriterien:
- Nachricht an Kontaktperson verfassen
- Kontaktformular ausfüllen

**Comment by meinkr4ft** [comment]
Kontaktaufnahme und Bestätigung sollen nach folgendem Sequenzdiagramm ablaufen:
![kontakt](https://user-images.githubusercontent.com/32766044/34007721-1be1853c-e103-11e7-8b1d-e8ef1a6cc3a1.png)

**Comment by lorenzstortz** [comment]
Passt.

**Comment by meinkr4ft** [comment]
Bei mir passts auch
