### ISSUE TITLE
Anmeldung

### ISSUE THREAD

**Issue by meinkr4ft** [sweIhm/sweiproject-tg1a-6#11]
Als Benutzer will ich mich verifizieren, damit ich bestimmte authorisierte Funktion des Acitvity Meter  in meiner aktuellen Sitzung nutzen kann.
Akzeptanzkriterien:
- Ich gebe meine HM- oder Cal Poly-E-mail-Adresse an
- Mir wird ein für kurze Zeit gültiger Verifizierungscode an die Hochschuladresse zugesandt
- Ich gebe den Verifizierungscode ein

**Comment by BullshitPingu** [comment]
Ich setze eine Authentifizierung mit Spring Boot und JSON Web Tokens (JWT) um, die RESTful sind im Gegensatz zur Benutzung eines Cookies.

**Comment by BullshitPingu** [comment]
Bisher wird für den Authentifizierungsprozess eine einfache Google Mail Adresse verwendet, es wäre allerdings wohl besser etwas anderes zu verwenden. Eine Möglichkeit ist SendGrid (https://sendgrid.com/).

**Comment by BullshitPingu** [comment]
Die Anmeldung soll nach folgendem UML umgesetzt werden.
![Anmeldung UML Diagramm](https://github.com/sweIhm/sweiproject-tg1a-6/blob/master/docs/resources/Anmeldung_UML.png)

**Comment by BullshitPingu** [comment]
Um den Entwicklungsprozess zu beschleunigen gibt es nun zwei Maven Profile dev (für Development) und prod (für Production).
Wenn man nun das Projekt mit clean install -P dev baut, wird keine Email mehr geschickt und jeder eingegebene Code wird erlaubt.
Das Profil prod ist standardmäßig aktiviert.

**Comment by BullshitPingu** [comment]
Durch die Email Authentifizierung sind Unit Tests in diesem Bereich nicht durchführbar ohne das Prinzip eines Blackboxtests zu verletzten. Man müsste den generierten Access Code aus dem Controller wissen.

**Comment by meinkr4ft** [comment]
![anmeldungsd](https://user-images.githubusercontent.com/32766044/33430625-7c5fc0a0-d5d1-11e7-9a9d-045e7cc43256.png)
