### ISSUE TITLE
Bestätigung bei erfolgreicher Kontaktaufnahme

### ISSUE THREAD

**Issue by BullshitPingu** [sweIhm/sweiproject-tg1a-6#13]
Als Benutzer möchte ich eine Bestätigung, falls die durch das Kontaktformular versendete Nachricht erfolgreich versendet worden konnte.

Akzeptanzkriterien:
- Bestätigungsnachricht nach dem Absenden über das Kontaktformular oder per E-Mail

**Comment by meinkr4ft** [comment]
Kontaktaufnahme und Bestätigung sollen nach folgendem Sequenzdiagramm ablaufen:
![kontakt](https://user-images.githubusercontent.com/32766044/34007721-1be1853c-e103-11e7-8b1d-e8ef1a6cc3a1.png)

**Comment by lorenzstortz** [comment]
Scheint zu funktionieren.
