### ISSUE TITLE
Filterung aufheben

### ISSUE THREAD

**Issue by BullshitPingu** [sweIhm/sweiproject-tg1a-6#14]
Als Benutzer möchte ich die Filterung von Aktivitäten mit einem Knopfdruck aufheben können um erneut alle Aktivitäten zu sehen.

Akzeptanzkriterien:
- Es existiert ein Knopf der sichtbar bei der Filterung platziert ist
- Es ist deutlich gemacht, dass dieser Knopf die Filterung aufhebt.
- Es soll durch den Nutzer bestätigt werden das die Filterung aufgehoben werden soll wenn man auf den Knopf drückt.
- Nach der Bestätigung der Bestätigungsnachricht soll die Filterung aufgehoben werden und wieder alle Aktivitäten angezeigt werden.

**Comment by meinkr4ft** [comment]
Filterung aufheben soll nach folgendem Sequenzdiagramm ablaufen:
![aufheben](https://user-images.githubusercontent.com/32766044/33919016-be50b0e8-dfb6-11e7-8b89-2fb653d3777a.png)

**Comment by BullshitPingu** [comment]
Beim Sequenzdiagramm fehlt noch die Server Beteiligung, immerhin kommen die gefilterten Aktivitäten vom Server.

**Comment by lorenzstortz** [comment]
Getestet: Funktioniert.
