### ISSUE TITLE
Vorschau für Aktivitätserstellung und -bearbeitung

### ISSUE THREAD

**Issue by BullshitPingu** [sweIhm/sweiproject-tg1a-6#15]
Als Benutzer möchte ich schon während der Erstellung und Bearbeitung einer Aktivität eine Rückmeldung haben, wie sich die Änderungen später Auswirken.

Akzeptanzkriterien:
- Es gibt eine Vorschau in direkter Nähe zum Formular der Aktivitätserstellung und -bearbeitung
- Die Vorschau zeigt tatsächlich wie die Aktivität später in der Detailansicht zu sehen ist.

**Comment by lorenzstortz** [comment]
Ist mit dem WYSIWYG-Editor erfüllt.
