### ISSUE TITLE
Aktivitätsdetails schließen

### ISSUE THREAD

**Issue by lorenzstortz** [sweIhm/sweiproject-tg1a-6#17]
Als Benutzer kann ich die Detailansicht einer Aktivität auch wieder schließen.

Akzeptanzkriterien:
-Ich kann die Detailansicht schließen.

**Comment by Fynian** [comment]
Funktion wird wie im [Aktivitätsdetails Schließen](sweiproject-tg1a-6/docs/resources/DetailsSchließen_UML.png) verwendet.
