### ISSUE TITLE
Internationalisierung der Anwendung

### ISSUE THREAD

**Issue by lorenzstortz** [sweIhm/sweiproject-tg1a-6#20]
Die Anwendung soll zusätzlich zur englischen Sprache auch auf Deutsch verfügbar sein.
Eventuell soll eine automatische Anpassung an die IP des Nutzers erfolgen.

Akzeptanzkriterien:
-Unterstützung von Deutsch und Englisch als wählbare Sprachen
-Erweiterbarkeit

**Comment by Fynian** [comment]
Die Englische Sprache wurde implementiert. Es liegen Fehler vor, die eine Implementierung in das Master noch verzögert. Derzeitige Fehler automatisierte Update der Language Datei sowie eine Umschaltung der Sprachen über Botton. Eine Lösungsvorschlag wäre Sprachpakete über den Server erstellen und über die zusätzliche Adressen Ergänzung ../en/activity für Englisch oder ../de/activity für Deutsch aufzurufen.
Die genaue Verwirklichung wird in der Gruppe abgesprochen und dann umgesetzt.

**Comment by Fynian** [comment]
Lösung für das Problem gefunden und wir derzeitig Implementiert. Tests konnten nicht erfolgen, da ich noch Technische Probleme besitze. Ich hab die aktuelle Version von heute genommen und erstelle für das jetzige Version die Sprach Dateien "DE" und "EN". Sobald ich die Probleme gefunden hab und die Tests auf meinem Rechner erfolgreich abgeschlossen hab, werde Mittwoch noch mal Updaten und schauen ob Veränderungen vorliegen. Falls ja werde ich diese auch zur Sprache hinzufügen. Weitere Komponenten, die ihr dann erstellt, bitte ich dann mit der Sprach Dateien selber zu verbinden. Wie und Wo ihr das machen könnt, gebe ich dann hier noch mal bescheid, sobald die Tests abgeschlossen sind.

**Comment by lorenzstortz** [comment]
feddich
