### ISSUE TITLE
Umbau auf Angular Material UI

### ISSUE THREAD

**Issue by BullshitPingu** [sweIhm/sweiproject-tg1a-6#24]
Um das Look & Feel der Webanwendung zu vereinheitlichen und bessere Unterstützung für mobile Browser zu erlangen können wir Angular Material UI verwenden.

https://material.angular.io

**Comment by BullshitPingu** [comment]
Angular Material UI ist eingebaut.

**Comment by lorenzstortz** [comment]
Funktioniert und sieht gut aus.

**Comment by meinkr4ft** [comment]
funktioniert bei mir ebenfalls
