### ISSUE TITLE
Alle Aktivitäten anschauen

### ISSUE THREAD

**Issue by BullshitPingu** [sweIhm/sweiproject-tg1a-6#4]
Als Benutzer will ich mir alle Aktivitäten des Activity Meters anzeigen lassen um zu sehen was aktuell an der Hochschule München und Cal Poly passiert.

Akzeptanzkriterien:
- Ich kann mir eine Liste aller Aktivitäten anzeigen lassen
- Die Liste ist nach dem Zeitpunkt der Erstellung sortiert
- Wenn keine Einträge vorhanden sind erscheint ein Hinweis

**Comment by lorenzstortz** [comment]
Als Standard-Sortierung sollten die Aktivitäten nach Aktualität (Datum der Erstellung/ letzte Bearbeitung) angezeigt werden.

**Comment by BullshitPingu** [comment]
Was hier sicherlich nützlich ist, ist ein Angular Observable um mitzubekommen wenn sich die Aktivitätenliste geändert hat.

Ein Beispiel: http://jasonwatmore.com/post/2016/12/01/angular-2-communicating-between-components-with-observable-subject

**Comment by meinkr4ft** [comment]
Aktivität bearbeiten soll nach folgendem Sequenzdiagramm ablaufen:
![anschauensd](https://user-images.githubusercontent.com/32766044/33452025-16ef932c-d611-11e7-82a9-0d432d71ec60.png)
