### ISSUE TITLE
Aktivität erstellen

### ISSUE THREAD

**Issue by BullshitPingu** [sweIhm/sweiproject-tg1a-6#5]
Als Benutzer des Activity Meters will ich Aktivitäten erstellen können damit ich meine aktuellen Projekte, etc. Hochschulübergreifend teilen kann.

Akzeptanzkriterien:
- Ich kann eine Aktivität erstellen, die Text, Bilder und Videos enthalten kann
- Der Verfasser soll anonym bleiben
- Ich kann eine Kontaktperson definieren
- Ich kann Schlagworte (Tags) definieren und anzeigen lassen
- Ich kann mir die erstellte Aktivität anzeigen lassen
- Ich kann eine Kategorie definieren und anzeigen

**Comment by lorenzstortz** [comment]
Die Einbindung eines WYSIWYG Editors erscheint sinnvoll,  um den Nutzer eine intuitive Möglichkeit zur Gestaltung seiner Aktivitäten zu geben.

**Comment by BullshitPingu** [comment]
Ich würde Froala vorschlagen (MIT Lizenz).
Hier eine Demo mit Inline Editor, die ich besonders gut finde: https://www.froala.com/wysiwyg-editor/inline

Github Repository: https://github.com/froala/angular-froala-wysiwyg

**Comment by BullshitPingu** [comment]
Im Moment geht JPA immer noch davon aus, dass der Inhalt einer Aktivität (String) auf einen Varchar(255) gemapped werden soll. Das ist allerdings falsch. In SQL steht meistens ein Datentyp text für unendlich lange Strings zur Verfügung.

Wir könnten die Größe des Varchars verändern mit der Annotation: 
`@Column(length=8000)
private String content;`

Alternativ kann man JPA auch mitteilen, dass es ein Text Typ sein soll mit:
`@Lob
@Column
private String content;`

`@Lob` bedeutet "Large Object", also wird der String auf ein BLOB (Binary Large Object) oder CLOB (Character large Object) gemapped, dass soll dann allerdings die Sorge von JPA sein.

**Comment by BullshitPingu** [comment]
Später soll nicht nur ein einfacher String als Inhalt reichen, sondern HTML angezeigt werden (Damit der Nutzer Text formatieren kann, Bilder und Videos hinzufügen, etc.). Zum Erstellen des HTML soll ein WYSIWYG Editor verwendet werden.

In Angular kann man HTML anzeigen, allerdings nicht über das übliche Doppel Binding mit 
``` js
{{activity.content}}
```

Beispiel:
``` html
<div [innerHTML]="activity.content"></div>
```

wobei activity.content ein HTML String ist.

**Comment by meinkr4ft** [comment]
Die Erstellung soll nach folgendem Seqeuenzdiagramm ablaufen 
![erstellensd](https://user-images.githubusercontent.com/32766044/33431429-9a905776-d5d4-11e7-8920-e8d588024547.png)

**Comment by BullshitPingu** [comment]
Als WYSIWYG Editor kommt Froala leider nicht mehr in Frage, da man offenbar eine Lizenz braucht um den Editor zu verwenden.

Als Alternative habe ich Quill gefunden: https://github.com/surmon-china/ngx-quill-editor.

**Comment by BullshitPingu** [comment]
http://www.buompris.co/ng2-tag-input/ Ist vielleicht das richtig zum Tags hinzufügen.

**Comment by lorenzstortz** [comment]
Getestet: Funktioniert.
