### ISSUE TITLE
Aktivitätsvisualisierungen anzeigen

### ISSUE THREAD

**Issue by lorenzstortz** [sweIhm/sweiproject-tg1a-6#6]
Als Benutzer will ich mir eine Visualisierung der Zusammenarbeit zwischen der Hochschule München und Cal Poly anzeigen lassen können.

Akzeptanzkriterien:
-Möglichkeit der Anzeige der Visualisierungen
-Fehlerinformationen ausgeben bei evtl. fehlendem Support des Browsers für die Visualiserungen

**Comment by lorenzstortz** [comment]
Zur einfachen Darstellung der Daten in Form von Graphen und Schaubildern können wir ng2-charts verwenden (https://github.com/valor-software/ng2-charts, MIT-Lizenz).

Falls in Zukunft komplexere Verhältnisse unsere Datenstruktur visualisiert werden sollen bietet sich die D3-Bibliothek dafür an (https://d3js.org).

**Comment by BullshitPingu** [comment]
ng2-charts reicht. Coole Sache mit Angular 2 - 5!

**Comment by lorenzstortz** [comment]
ng2-charts hat enorme Probleme mit dem asynchronen Laden von Daten. 
Evtl. Umstieg auf ngx-charts(https://github.com/swimlane/ngx-charts, MIT-Lizenz).

**Comment by meinkr4ft** [comment]
Aktivitätsvisualisierungen anzeigen soll nach folgendem Sequenzdiagramm ablaufen:
![visualisierung](https://user-images.githubusercontent.com/32766044/34007678-eb0d067a-e102-11e7-8090-2a3e80b44447.png)

**Comment by lorenzstortz** [comment]
Nach weiterem Ausprobieren von Bibliotheken scheint PrimeNG am besten zu funktionieren, welches ebenfalls unter der MIT-Lizenz zur Verfügung steht.

https://www.primefaces.org/primeng
