### ISSUE TITLE
Aktivität bearbeiten

### ISSUE THREAD

**Issue by lorenzstortz** [sweIhm/sweiproject-tg1a-6#7]
Als Benutzer will ich eine von mir erstellte Aktivität überarbeiten können und auch die Möglichkeit haben diese zu löschen.

Akzeptanzkriterien:

-Ich kann eine Aktivität überarbeiten inklusive Text, Bilder und Videos
-Ich kann eine Aktitvität löschen
-Ich kann nur meine eigenen Aktivitäten bearbeiten

**Comment by meinkr4ft** [comment]
Aktivität bearbeiten soll nach folgendem Sequenzdiagramm ablaufen: 
![bearbeitensd](https://user-images.githubusercontent.com/32766044/33431470-bbf79f64-d5d4-11e7-8c02-071d29519df1.png)

**Comment by lorenzstortz** [comment]
Getestet: Funktioniert.
