### ISSUE TITLE
Aktivitäten filtern

### ISSUE THREAD

**Issue by Fynian** [sweIhm/sweiproject-tg1a-6#8]
Als Benutzer will ich alle Aktivitäten nach bestimmte Kriterien filtern. Diese können vorgegeben (Datum der Erstellung) oder eigene Eingaben, die dann mit dem Titel verglichen wird.

Akzeptanzkriterien:
-Ich kann nach Datum der Erstellung von Aktivitäten filtern.
-Ich kann Schlüsselwörter eingeben, die dann mit dem Titel verglichen wird.
-Wenn keine Aktivitäten zu der angegebene Filter passen, erscheint ein Hinweis.

**Comment by meinkr4ft** [comment]
Aktivitäten filtern soll nach folgendem Sequenzdiagramm ablaufen:
![filtern](https://user-images.githubusercontent.com/32766044/33919040-d6681d56-dfb6-11e7-9aaf-c5db1714c7a4.png)

**Comment by BullshitPingu** [comment]
Beim Sequenzdiagramm fehlt noch die Server Beteiligung, immerhin kommen die gefilterten Aktivitäten vom Server.

**Comment by lorenzstortz** [comment]
Getestet: Funktioniert.
